# Generated by Django 5.0.4 on 2024-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BATModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOC', models.FloatField()),
                ('SOH', models.FloatField()),
                ('vol', models.FloatField()),
                ('cur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PCSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_power', models.FloatField()),
                ('frequency', models.FloatField()),
                ('R_vol', models.FloatField()),
                ('S_vol', models.FloatField()),
                ('T_vol', models.FloatField()),
                ('R_cur', models.FloatField()),
                ('S_cur', models.FloatField()),
                ('T_cur', models.FloatField()),
            ],
        ),
    ]
